import {create} from 'zustand'; import {workflows as seed} from '../../mock-data/workflows'; import {instances} from '../../mock-data/instances'; import type {FlowEdge,FlowNode,MigrationBatch,ValidationIssue,Workflow} from '../types'; import {loadBatches,planBatch,readServer,resolveVersion,runBatch,writeServer} from './migration';
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const validate=(w:Workflow):ValidationIssue[]=>{const issues:ValidationIssue[]=[]; if(!w.nodes.some(n=>n.type==='end')) issues.push({nodeId:w.nodes[0]?.id||'flow',level:'error',message:'流程缺少结束节点'}); const linked=new Set(w.edges.flatMap(e=>[e.source,e.target])); w.nodes.filter(n=>n.type!=='start'&&n.type!=='end'&&!linked.has(n.id)).forEach(n=>issues.push({nodeId:n.id,level:'error',message:'必经节点不能孤立'})); w.nodes.forEach(n=>{if(n.type==='condition'&&!n.data.config.ruleType)issues.push({nodeId:n.id,level:'error',message:'条件分支规则未配置'}); if(n.type==='approval'&&!n.data.config.approverSource)issues.push({nodeId:n.id,level:'error',message:'审批人不能为空'});}); return issues};
interface State{workflows:Workflow[];instances:typeof instances;currentId:string;selectedNodeId:string|null;issues:ValidationIssue[];toast:string;batches:MigrationBatch[];simulateFailure:boolean;setCurrent:(id:string)=>void;selectNode:(id:string|null)=>void;updateNodes:(nodes:FlowNode[])=>void;updateEdges:(edges:FlowEdge[])=>void;updateConfig:(id:string,config:Record<string,any>)=>void;runValidation:()=>ValidationIssue[];save:()=>void;publish:()=>void;create:()=>string;copy:(id:string)=>void;archive:(id:string)=>void;restore:(v:number)=>void;clearToast:()=>void;planMigration:(workflowId:string)=>void;submitMigration:(id:string)=>void;retryMigration:(id:string)=>void;setSimulateFailure:(v:boolean)=>void}
export const useAppStore=create<State>((set,get)=>{
 const exec=(id:string,retry:boolean)=>{const s=get(),b=s.batches.find(x=>x.id===id);if(!b)return;const server=readServer();const r=runBatch(b,s.instances,s.simulateFailure,server);const batches=s.batches.map(x=>x.id===id?r.batch:x);writeServer({...server,tokens:r.tokens,versions:r.versions,batches});const{migrated,conflict,broken}=r.stats;set({instances:r.instances,batches,simulateFailure:broken?false:s.simulateFailure,toast:broken?`批次写入失败：已迁移 ${migrated} 个，其余保留待办可重试`:conflict?`${migrated} 个已迁移，${conflict} 个版本冲突保留待办`:migrated?`${retry?'重试补迁':'批次提交'}完成：${migrated} 个实例已迁移`:'没有可迁移的待办实例'})};
 return{workflows:clone(seed),instances,currentId:'wf-1',selectedNodeId:null,issues:[],toast:'',batches:loadBatches(),simulateFailure:false,
 setCurrent:id=>set({currentId:id,selectedNodeId:null,issues:[]}),
 selectNode:id=>set({selectedNodeId:id}),
 updateNodes:nodes=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes}:w)})),
 updateEdges:edges=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,edges}:w)})),
 updateConfig:(id,config)=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,nodes:w.nodes.map(n=>n.id===id?{...n,data:{...n.data,config:{...n.data.config,...config},state:'configuring'}}:n)}:w)})),
 runValidation:()=>{const w=get().workflows.find(x=>x.id===get().currentId)!; const issues=validate(w); set(s=>({issues,workflows:s.workflows.map(x=>x.id===w.id?{...x,nodes:x.nodes.map(n=>({...n,data:{...n.data,state:issues.some(i=>i.nodeId===n.id)?'invalid':'valid'}}))}:x),toast:issues.length?`发现 ${issues.length} 个问题`:'校验通过'}));return issues},
 save:()=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'draft',updatedAt:'2026-07-11 16:30'}:w),toast:'草稿已保存'})),
 publish:()=>set(s=>({workflows:s.workflows.map(w=>w.id===s.currentId?{...w,status:'published',version:w.version+1,publishedAt:'2026-07-11 16:35',updatedAt:'2026-07-11 16:35',versions:[...w.versions,{version:w.version+1,createdAt:'2026-07-11 16:35',note:'发布最新审批配置',nodes:clone(w.nodes),edges:clone(w.edges)}]}:w),toast:'流程发布成功'})),
 create:()=>{const id='wf-'+Date.now();set(s=>({workflows:[{id,name:'未命名流程',domain:'财务',status:'draft',version:0,editor:'林秋',updatedAt:'2026-07-11 16:40',abnormalCount:0,nodes:[],edges:[],versions:[]},...s.workflows],currentId:id}));return id},
 copy:id=>set(s=>{const w=s.workflows.find(x=>x.id===id)!;return{workflows:[{...clone(w),id:'wf-'+Date.now(),name:w.name+'（副本）',status:'draft'},...s.workflows]}}),
 archive:id=>set(s=>({workflows:s.workflows.map(w=>w.id===id?{...w,status:'archived'}:w)})),
 restore:v=>set(s=>({workflows:s.workflows.map(w=>{if(w.id!==s.currentId)return w;const old=w.versions.find(x=>x.version===v)!;return{...w,status:'draft',nodes:clone(old.nodes),edges:clone(old.edges)}}),toast:`已恢复 v${v} 为草稿`})),
 clearToast:()=>set({toast:''}),
 planMigration:workflowId=>{const s=get(),w=s.workflows.find(x=>x.id===workflowId);if(!w)return;const server=readServer(),backfilled=new Set<string>();const instances=s.instances.map(i=>{if(i.workflowId!==workflowId)return i;const v=server.versions[i.id]??i.version??resolveVersion(i,w);if(v!=null&&i.version==null)backfilled.add(i.id);return v!=null&&v!==i.version?{...i,version:v}:i});const batch=planBatch(w,instances,s.batches.length+1,server,backfilled),batches=[...s.batches,batch];writeServer({...server,batches});const c=(st:string)=>batch.items.filter(i=>i.status===st).length;set({instances,batches,toast:`批次 ${batch.id} 已生成：${c('pending')} 个可迁移 · ${c('skipped')} 个保留 · ${c('unresolved')} 个待处理`})},
 submitMigration:id=>exec(id,false),
 retryMigration:id=>exec(id,true),
 setSimulateFailure:v=>set({simulateFailure:v})};
});
